### ISSUE TITLE
Please add a redirect to the new location

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang-nursery/rust-cookbook#262]
People new to programming do not know how to rewrite a pg-pages url to the repo url and can not find the new location.

The old location mentioned in the blog: https://brson.github.io/rust-cookbook/

Regards

**Comment by budziq** [comment]
Hi @dns2utf8,

Unfortunately the old gh-pages address stopped existing due to repository transfer into rust-lang-nursery and there is not much we can do about it as brson will not be available for some time to operate his repositories.

The best we can do at the moment is announce the new address to the audience in the mailing lists and reddit. Which blog post do you mean? I might be able to reach out to someone with proper rights to edit the post.

**Comment by dns2utf8** [comment]
Hi @budziq 

Thank you for the fast reply.

I mean this blog post https://github.com/rust-lang/blog.rust-lang.org/pull/191
The urls are silently updated, no **[Updated YYYY-MM-DD]** tag yet.

Would be great if you could ping somebody

**Comment by budziq** [comment]
Hi @dns2utf8

I'm sorry for taking so long to get back to you on this. Basically I'm waiting for Rust lang stakeholders decision if this new url will be final or even semi final before moving on with any announcements.

cc @aturon

**Comment by aturon** [comment]
Hey @budziq, sorry for the delay. This url is semi-final; it's where the cookbook will live until we "publish" it toward the end of the year (at which point it will be promoted to rust-lang proper).

Sorry about the lack of heads-up about this.

**Comment by budziq** [comment]
Ok I've advertised the move on [URLO](https://users.rust-lang.org/t/rust-cookbook-needs-a-lot-of-help/10841/4?u=budziq), [IRLO](https://internals.rust-lang.org/t/rust-libz-blitz/5184/131?u=budziq) and [rust reddit](https://www.reddit.com/r/rust/comments/6rjm60/rust_cookbook_has_a_new_home_rustlangnursery/)
@dns2utf8 If you have any other channel that I might use in mind please do not hesitate to contact me :)
