### ISSUE TITLE
Recipe: custom type implements FromStr

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#400]
|  |  |
| ------------- | ------------- |
| Crates  | std  |
| Section  | 16.2 String Parsing  |

Create a custom type that implements FromStr.  An example would be IPv4Address.  This could be an email address, splitting on the '@', or separating first,middle (optional), and last names (this is really hard internationally, but a contrived example might be helpful).

**Comment by NiekGr** [comment]
This isn't labelled "easy", but can I work on this?

**Comment by AndyGauge** [comment]
You can.  It isn't all that hard actually.  I'm just not very good at labelling.

**Comment by NiekGr** [comment]
Oké, thank you Andy

**Comment by NiekGr** [comment]
Hi @AndyGauge,

Should I only do simple parsing, or can I also use parser library (not that complex)?

Thank you

**Comment by budziq** [comment]
Hi. I'd suggest to avoid introducing new crates to cookbook if the task can be done with pure std with comparable complexity.

**Comment by NiekGr** [comment]
I thought a lot about what to do. You mentioned IPv4, but I thought it was a too simple. So I tried to make an IPv6 parser, but I have no idea how to do this in a rust ideology.

With my vacation coming up, I will try to work a little harder on this.

**Comment by budziq** [comment]
@NiekGr 
I'd suggest to avoid using IPv6 parsing as an example as it is surprisingly complex and correct implementation would take a lot of code completely irrelevant to the relatively trivial `FromStr` toppic.
Moreover, there is already an [implementation in stdlib](https://doc.rust-lang.org/src/std/net/parser.rs.html#184), IPv6 (and IPv4 for that matter) example could lead new rustaceans to believe that one has to implement such parser from scratch. 
- If we stick to the IPv4 route which would be both trivial and to the point, we would need to explicitly mark this example as a toy code not to be used in production
- otherwise we could provide a parser from equally trivial topic like hex/web color [specification subset](https://www.w3.org/TR/CSS21/syndata.html#color-units)

**Comment by AndyGauge** [comment]
Honestly, the stdlib's example https://doc.rust-lang.org/std/str/trait.FromStr.html#examples is pretty good, I just wanted something in the cookbook to demonstrate some of std features that could help a wide audience (as not many people read std docs like a book).

+1 for converting a string of 6 hex characters into a Red Green and Blue struct.

**Comment by NiekGr** [comment]
@budzig @AndyGauge I really like the web colour parsing. And I have a much better idea how to do that. Thank you for the idea, I will work it out.

Have a good evening.

**Comment by KappaDistributive** [comment]
Since this issue seems to be vacant, I'd like to pick it up.

But I'm not sure where is should go in the new structure of the book. I'm thinking to insert it as 

> 18 Text Processing / 18.2 String Parsing
