### ISSUE TITLE
Recipe: Creating Database in File System

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#453]
|  |  |
| ------------- | ------------- |
| Crates  | rusqlite|
| Section  | 7.1 SQLite  |

This recipe should demonstrate using rusqlite by saving the database to the file system.

**Comment by lnicola** [comment]
Can I take this one? Though I'm not really sure how it would end up like, since creating the database doesn't take much (you just have to open it AFAIK). Maybe it should be combined with #454.

PS: What does "Section: 7.1 SQLite" mean? Right now, Section 7.1 is "Date and Time / Duration and Calculation".

**Comment by AndyGauge** [comment]
Section 7 is Database, it doesn't exist yet.  That will make Date Time turn into section 8.  You can combine them into a single PR.  I separated them in case you were going for hacktoberfest.

**Comment by lnicola** [comment]
One stupid question: does it need `mdbook 0.1.8`? When I try to build it, I don't get a `book.css` file, so the styles are missing.

**Comment by lnicola** [comment]
Yeah, that was it. Nevermind.

**Comment by AndyGauge** [comment]
So I have additional interest in #454, let me know if you would like to claim 454, and if so, could you provide the structure so they could work on 455.

**Comment by lnicola** [comment]
This was closed by mistake, can you please reopen it?
