### ISSUE TITLE
Add a Run button to every example

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-cookbook#87]
We used to have one but it didn't work: https://github.com/brson/rust-cookbook/issues/32.

We could use an approach more like https://serde.rs where it links to a playground rather than running the code inline. See [this page](https://serde.rs/custom-date-format.html) for example. This is nice because you get to modify the code if you want.

**Comment by budziq** [comment]
As discussed on Use the crates from the libz blitz? integer32llc/rust-playground#168 the integer32 rust playground team is willing to coordinate with us on the list of preloaded crates.

Cookbook would be also interested on a json  list of supported crates that we could consume in runtime to (re)enable play buttons for given examples.

As suggested by @kodraus one or both parties might expose static json lists via raw github content.
What is left is to discuss the details.

cc @shepmaster

**Comment by shepmaster** [comment]
The static lists I could go either way on. That is, if we want to say that the cookbook libs *should* be in the playground, I'm cool with that. We can add a whitelist easily. Then we could just accept a PR every time a library goes though the blitz. I don't know if we want to *start* with worrying about if this crate available or not - just assume all are. A thing that would change my mind would be if we know there are incompatibilities.

**Comment by budziq** [comment]
I guess that I would prefer to treat the playpen as semi volatile remote resource as we might add some non blitz crates to cookbook examples and We might want to query the playpen for supported crates prior to enabling play buttons on per example basis.

Having a whitelist would be awesome as we would be able to setup a curation process for the crate list. And we would just push a PR once crate is within the Libz Blitz. Could you specify the form (and possibly create a whitelist stub where you'd like to have it located)

Unfortunately I'll not be able to followup on this for the next two weeks due to holidays but someone from blitz might [take it up in the meantime](https://internals.rust-lang.org/t/rust-libz-blitz/5184/121?u=budziq)

**Comment by budziq** [comment]
fixed by update of mdbook
